const projectList = [
  {
    id: 1,
    name: "404 page design",
    category: ["js", "jquery"],
    image: require("../assets/projects/project1.png"),
    link: "https://t404nf.netlify.app/",
    source: "https://github.com/TahirAhmad01/404_page_design",
  },
  {
    id: 2,
    name: "todo application",
    category: ["react", "redux"],
    image: require("../assets/projects/project2.png"),
    link: "https://t404nf.netlify.app/",
    source: "https://github.com/TahirAhmad01/404_page_design",
  },
  {
    id: 3,
    name: "todo application",
    category: ["react", "firebase"],
    image: require("../assets/projects/project3.png"),
    link: "https://t404nf.netlify.app/",
    source: "https://github.com/TahirAhmad01/404_page_design",
  },
  {
    id: 4,
    name: "portfolio",
    category: ["js"],
    image: require("../assets/projects/project4.png"),
    link: "https://t404nf.netlify.app/",
    source: "https://github.com/TahirAhmad01/404_page_design",
  },
  {
    id: 5,
    name: "Android by html",
    category: ["js", "jquery"],
    image: require("../assets/projects/project5.png"),
    link: "https://t404nf.netlify.app/",
    source: "https://github.com/TahirAhmad01/404_page_design",
  },
  {
    id: 6,
    name: "Android by html",
    category: ["js", "jquery"],
    image: require("../assets/projects/project6.png"),
    link: "https://t404nf.netlify.app/",
    source: "https://github.com/TahirAhmad01/404_page_design",
  },
  {
    id: 7,
    name: "Android by html",
    category: ["js", "jquery"],
    image: require("../assets/projects/project7.png"),
    link: "https://t404nf.netlify.app/",
    source: "https://github.com/TahirAhmad01/404_page_design",
  },
  {
    id: 8,
    name: "Android by html",
    category: ["js", "jquery"],
    image: require("../assets/projects/project8.png"),
    link: "https://t404nf.netlify.app/",
    source: "https://github.com/TahirAhmad01/404_page_design",
  },
  {
    id: 9,
    name: "Android by html",
    category: ["js", "jquery"],
    image: require("../assets/projects/project9.png"),
    link: "https://t404nf.netlify.app/",
    source: "https://github.com/TahirAhmad01/404_page_design",
  },
];

export default projectList;
